import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="qara" >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  text-base-content w-min-sm`}
        >
          {/* 顶部导航 */}
          <div className="bg-base-100 w-full px-2 md:px-4 lg:px-8 xl:px-16 2xl:px-26">
            <NavBar />
          </div>

          {/* 主内容区域 */}
          <div className="bg-base-100 px-2 md:px-4 lg:px-8 xl:px-16 2xl:px-26">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
